spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spyglass
    username: root
    password: root1234
    


logging:
  level:
    com:
      skillstorm:
        demo: debug
    org:
      springframework:
        web: INFO
        security: INFO